### ISSUE TITLE
Correct speaker names in the program page

### ISSUE THREAD

**Issue by armin-bauer** [eloop-congress/eloop.org#1]
Hi guys,

great idea for a conference, thanks for hosting it. 
I think you made a small typo in the program schedule, the name of the speaker should probably be

Nene Plese

instead of 

Nele Plese

Good luck with the conference :+1:

**Comment by makefu** [comment]
closed with https://github.com/eloop-congress/website_templates/commit/848d4e76ed41db6afddaf59cdfc89a3168cd8c4e
