### ISSUE TITLE
Substantive großschreiben

### ISSUE THREAD

**Issue by bronsen** [eloop-congress/eloop.org#2]
> zur verfügung

ist nicht ganz richtig: im deutschen werden Substantive großgeschrieben. Manche Substantive erkennt man recht einfach daran, dass sie auf "-ung" enden.

Hier muss das keine "v" durch ein großes "V" ersetzt werden.
## 

der Rechtschreibnazi hat gesprochen

**Comment by makefu** [comment]
closed with https://github.com/eloop-congress/website_templates/commit/86c1202134fa61e36dc69c3baf504610a459ee50
